const ADD_EXPENSES = 'ADD_EXPENSES';
const DELETE_EXPENSES = 'DELETE_EXPENSES';
const CLEAR_EXPENSES = 'CLEAR_EXPENSES';
const GET_EXPENSES = 'GET_EXPENSES';

export {
    ADD_EXPENSES,
    DELETE_EXPENSES,
    CLEAR_EXPENSES,
    GET_EXPENSES
}