const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';
const PARENT_REQUEST = 'PARENT_REQUEST';
const PARENT_REQUEST_SUCCESS = 'PARENT_REQUEST_SUCCESS';
const PARENT_REQUEST_FAILURE = 'PARENT_REQUEST_FAILURE';
const REGiSTER_REQUEST = 'REGiSTER_REQUEST';
const REGiSTER_REQUEST_SUCCESS = 'REGiSTER_REQUEST_SUCCESS';
const REGiSTER_REQUEST_FAILURE = 'REGiSTER_REQUEST_FAILURE';
const CHILD_REQUEST = 'CHILD_REQUEST';
const CHILD_REQUEST_SUCCESS = 'CHILD_REQUEST_SUCCESS';
const CHILD_REQUEST_FAILURE = 'CHILD_REQUEST_FAILURE';
const ADD_CHILD_REQUEST = 'ADD_CHILD_REQUEST';
const ADD_CHILD_REQUEST_SUCCESS = 'ADD_CHILD_REQUEST_SUCCESS';
const ADD_CHILD_REQUEST_FAILURE = 'ADD_CHILD_REQUEST_FAILURE';
const ADD_PARENT_REQUEST = 'ADD_PARENT_REQUEST';
const ADD_PARENT_REQUEST_SUCCESS = 'ADD_PARENT_REQUEST_SUCCESS';
const ADD_PARENT_REQUEST_FAILURE = 'ADD_PARENT_REQUEST_FAILURE';
const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
const UPDATE_USER_REQUEST_SUCCESS = 'UPDATE_USER_REQUEST_SUCCESS';
const UPDATE_USER_REQUEST_FAILURE = 'UPDATE_USER_REQUEST_FAILURE';
const UPDATE_CHILD_REQUEST = 'UPDATE_CHILD_REQUEST';
const UPDATE_CHILD_REQUEST_SUCCESS = 'UPDATE_CHILD_REQUEST_SUCCESS';
const UPDATE_CHILD_REQUEST_FAILURE = 'UPDATE_CHILD_REQUEST_FAILURE';
const ADD_CHILD_DETAILS = 'ADD_CHILD_DETAILS';
const ADD_PARENT_DETAILS = 'ADD_PARENT_DETAILS';
const ADD_CHILD_IMAGE = 'ADD_CHILD_IMAGE;'
const ADD_IMAGE = 'ADD_IMAGE';

export {
  LOGIN_REQUEST,
  LOGIN_REQUEST_SUCCESS,
  LOGIN_REQUEST_FAILURE,
  PARENT_REQUEST,
  PARENT_REQUEST_SUCCESS,
  PARENT_REQUEST_FAILURE,
  ADD_PARENT_REQUEST,
  ADD_PARENT_REQUEST_SUCCESS,
  ADD_PARENT_REQUEST_FAILURE,
  REGiSTER_REQUEST,
  REGiSTER_REQUEST_SUCCESS,
  REGiSTER_REQUEST_FAILURE,
  CHILD_REQUEST,
  CHILD_REQUEST_SUCCESS,
  CHILD_REQUEST_FAILURE,
  ADD_CHILD_REQUEST,
  ADD_CHILD_REQUEST_SUCCESS,
  ADD_CHILD_REQUEST_FAILURE,
  UPDATE_USER_REQUEST,
  UPDATE_USER_REQUEST_SUCCESS,
  UPDATE_USER_REQUEST_FAILURE,
  UPDATE_CHILD_REQUEST,
  UPDATE_CHILD_REQUEST_SUCCESS,
  UPDATE_CHILD_REQUEST_FAILURE,
  ADD_PARENT_DETAILS,
  ADD_CHILD_DETAILS,
  ADD_CHILD_IMAGE,
  ADD_IMAGE
}